<a href="https://colab.research.google.com/github/chinmaya386/Assignmets-python-/blob/main/Pandas3class.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import pandas as pd 

In [ ]:
data = {'name' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        'salary' : [100 , 200 , 300 , 400],
        'mail_id' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        'addr' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [ ]:
df=pd.DataFrame(data)

In [ ]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [ ]:
df.loc[1:3]

name  salary             mail_id addr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [ ]:
df.iloc[1:3]

name  salary            mail_id addr
1   krish     200   krish@ineuron.ai  blr
2  hitesh     300  hitesh@ineuron.ai  blr

In [ ]:
data1= {'pf_nu' : [234,45,54465,656],
        'income_tax' : [234,565,767,6778],
        'mobile_no' : [23543,43543,454,5656],
        'courses' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    
}

In [ ]:
df1=pd.DataFrame(data1)

In [ ]:
df1

pf_nu  income_tax  mobile_no     courses
0    234         234      23543          ds
1     45         565      43543     bigdata
2  54465         767        454    web dev 
3    656        6778       5656  blockchian

In [ ]:
df

name  salary             mail_id addr
0     sudh     100     sudh@ineuron.ai  blr
1    krish     200    krish@ineuron.ai  blr
2   hitesh     300   hitesh@ineuron.ai  blr
3  tulesko     400  tulesko@ineuron.ai  mum

In [ ]:
pd.concat([df,df1])

name  salary             mail_id addr    pf_nu  income_tax  mobile_no  \
0     sudh   100.0     sudh@ineuron.ai  blr      NaN         NaN        NaN   
1    krish   200.0    krish@ineuron.ai  blr      NaN         NaN        NaN   
2   hitesh   300.0   hitesh@ineuron.ai  blr      NaN         NaN        NaN   
3  tulesko   400.0  tulesko@ineuron.ai  mum      NaN         NaN        NaN   
0      NaN     NaN                 NaN  NaN    234.0       234.0    23543.0   
1      NaN     NaN                 NaN  NaN     45.0       565.0    43543.0   
2      NaN     NaN                 NaN  NaN  54465.0       767.0      454.0   
3      NaN     NaN                 NaN  NaN    656.0      6778.0     5656.0   

      courses  
0         NaN  
1         NaN  
2         NaN  
3         NaN  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [ ]:
pd.concat([df,df1],axis=1)

name  salary             mail_id addr  pf_nu  income_tax  mobile_no  \
0     sudh     100     sudh@ineuron.ai  blr    234         234      23543   
1    krish     200    krish@ineuron.ai  blr     45         565      43543   
2   hitesh     300   hitesh@ineuron.ai  blr  54465         767        454   
3  tulesko     400  tulesko@ineuron.ai  mum    656        6778       5656   

      courses  
0          ds  
1     bigdata  
2    web dev   
3  blockchian

In [ ]:
data2 = {'0' : ['sudh' , 'krish' , 'hitesh' , 'tulesko'],
        '1' : [100 , 200 , 300 , 400],
        '2' : ['sudh@ineuron.ai' , 'krish@ineuron.ai' , 'hitesh@ineuron.ai' , 'tulesko@ineuron.ai'],
        '3' : ['blr' , 'blr' , 'blr' , 'mum']
    }

In [ ]:
data3= {'0' : [234,45,54465,656],
        '1' : [234,565,767,6778],
        '2' : [23543,43543,454,5656],
        '3' : ['ds' , 'bigdata' , 'web dev ' , 'blockchian']
    }

In [ ]:
df2=pd.DataFrame(data2)

In [ ]:
df3=pd.DataFrame(data3)

In [ ]:
pd.concat([df2,df3])

0     1                   2           3
0     sudh   100     sudh@ineuron.ai         blr
1    krish   200    krish@ineuron.ai         blr
2   hitesh   300   hitesh@ineuron.ai         blr
3  tulesko   400  tulesko@ineuron.ai         mum
0      234   234               23543          ds
1       45   565               43543     bigdata
2    54465   767                 454    web dev 
3      656  6778                5656  blockchian

In [ ]:
data4 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }

In [ ]:
data5  = {'emp_id' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
    
}

In [ ]:
df4 = pd.DataFrame(data4)

In [ ]:
df4

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [ ]:
df5 = pd.DataFrame(data5)

In [ ]:
pd.merge(df4,df5 ,  how ='left')

emp_id  salary  pf  mob_no  house_nu
0     101     234  23  3434.0     345.0
1     102     345  34  5656.0     345.0
2     103     200  56     NaN       NaN
3     104     400  78   767.0     345.0

In [ ]:
pd.merge(df4,df5 ,  how ='right')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [ ]:
pd.merge(df4, df5  , how = 'right' , on = 'emp_id')

emp_id  salary    pf  mob_no  house_nu
0     101   234.0  23.0    3434       345
1     102   345.0  34.0    5656       345
2     104   400.0  78.0     767       345
3     105     NaN   NaN     878        56

In [ ]:
data6 = {'emp_id1' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data7  = {'emp_id2' : [101,102,104,105],
          'mob_no' : [3434,5656,767,878],
          'house_nu' : [345,345,345,56]
}

In [ ]:
df6 = pd.DataFrame(data6)

In [ ]:
df7=pd.DataFrame(data7)

In [ ]:
df6

emp_id1  salary  pf
0      101     234  23
1      102     345  34
2      103     200  56
3      104     400  78

In [ ]:
df7

emp_id2  mob_no  house_nu
0      101    3434       345
1      102    5656       345
2      104     767       345
3      105     878        56

In [ ]:
pd.merge(df6,df7 , left_on='emp_id1' , right_on='emp_id2',how = 'inner')

emp_id1  salary  pf  emp_id2  mob_no  house_nu
0      101     234  23      101    3434       345
1      102     345  34      102    5656       345
2      104     400  78      104     767       345

In [ ]:
data8 = {'emp_id' : [101,102,103,104],
         'salary' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data9  = {'emp_id' : [101,102,104,105,123],
          'salary' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
    
}

In [ ]:
df8 = pd.DataFrame(data8)

In [ ]:
df9 = pd.DataFrame(data9)

In [ ]:
df8

emp_id  salary  pf
0     101     234  23
1     102     345  34
2     103     200  56
3     104     400  78

In [ ]:
df9

emp_id  salary  house_nu
0     101     234       345
1     102     345       345
2     104     200       345
3     105     878        56
4     123      43       234

In [ ]:
pd.merge(df8,df9 , on = ['emp_id' , 'salary'])

emp_id  salary  pf  house_nu
0     101     234  23       345
1     102     345  34       345

In [ ]:
data10 = {'emp_id1' : [101,102,103,104],
         'salary1' : [234, 345,200,400],
         'pf' : [23,34,56,78],
         }
         
data11  = {'emp_id2' : [101,102,104,105,123],
          'salary2' : [234, 345,200,878,43],
          'house_nu' : [345,345,345,56,234]
    
}

In [ ]:
df10 = pd.DataFrame(data10,index=['a' ,'b','c' ,'d'])

In [ ]:
df11 = pd.DataFrame(data11,index=['a','b','d','e','f'])

In [ ]:
df10

emp_id1  salary1  pf
a      101      234  23
b      102      345  34
c      103      200  56
d      104      400  78

In [ ]:
df11

emp_id2  salary2  house_nu
a      101      234       345
b      102      345       345
d      104      200       345
e      105      878        56
f      123       43       234

In [ ]:
df10.join(df11)

emp_id1  salary1  pf  emp_id2  salary2  house_nu
a      101      234  23    101.0    234.0     345.0
b      102      345  34    102.0    345.0     345.0
c      103      200  56      NaN      NaN       NaN
d      104      400  78    104.0    200.0     345.0

In [4]:
df_sales  = pd.read_csv("/content/sales_data_final.csv")

In [5]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

          category sub_category                 product_name sales quantity  \
0  Office Supplies      Storage          Tenex Lockers, Blue   408        2   
1  Office Supplies     Supplies     Acme Trimmer, High Speed   120        3   
2  Office Supplies      Storage      Tenex Box, Single Width    66        4   
3  Office Supplies        Paper  Enermax Note Cards, Premium    45        3   
4        Furniture  Furnishings   Eldon Light Bulb, Duo Pack   114        5   

   discount   profit  shipping_cost  order_priority  year  
0       0.0  106.140          35.46          Medium  2011  
1       0.1   36.036           9.72          Medium  2011  
2       0.0   29.640           8.17            High  2011  
3       0.5  -26.055           4.82            High  2011  
4       0.1   37.770           4.70          Medium  2011  

[5 rows x 21 columns]

In [6]:
def profit_flag(a) : 
    if a >= 0 :
        return 'positive' 
    else :
        return 'negative'

In [7]:
profit_flag(-45)

'negative'

In [8]:
profit_flag(46)

'positive'

In [9]:
df_sales['flag_profit'] = df_sales['profit'].apply(profit_flag)

In [10]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sub_category  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...      Storage   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...     Supplies   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...      Storage   
3  Home Office        Stockholm     Sweden      EU    North  ...        Paper   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...  Furnishings   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year flag_profit  
0          35.46          Medium  2011    positive  
1           9.72          Medium  2011    positive  
2           8.17            High  2011    positive  
3           4.82            High  2011    negative  
4           4.70          Medium  2011    positive  

[5 rows x 22 columns]

In [11]:
df_sales['len_cust_name'] = df_sales['customer_name'].apply(len)

In [12]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ...  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...   
3  Home Office        Stockholm     Sweden      EU    North  ...   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   

                  product_name sales quantity discount   profit  \
0          Tenex Lockers, Blue   408        2      0.0  106.140   
1     Acme Trimmer, High Speed   120        3      0.1   36.036   
2      Tenex Box, Single Width    66        4      0.0   29.640   
3  Enermax Note Cards, Premium    45        3      0.5  -26.055   
4   Eldon Light Bulb, Duo Pack   114        5      0.1   37.770   

   shipping_cost  order_priority  year  flag_profit len_cust_name  
0          35.46          Medium  2011     positive            15  
1           9.72          Medium  2011     positive            11  
2           8.17            High  2011     positive            13  
3           4.82            High  2011     negative            12  
4           4.70          Medium  2011     positive            11  

[5 rows x 23 columns]

In [13]:
def quantity_flag(a) : 
    if  a < 10 :
        return 'low'
    elif a >10 and a <20 :
        return 'medium'
    else :
        return 'high'

In [14]:
df_sales['flag_quantity']= df_sales['quantity'].apply(quantity_flag)

In [18]:
df_sales.head(25)

order_id order_date ship_date       ship_mode      customer_name  \
0      AG-2011-2040   1/1/2011  1/6/2011  Standard Class    Toby Braunhardt   
1     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
2      HU-2011-1220   1/1/2011  1/5/2011    Second Class      Annie Thurman   
3   IT-2011-3647632   1/1/2011  1/5/2011    Second Class       Eugene Moren   
4     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
5     IN-2011-47883   1/1/2011  1/8/2011  Standard Class        Joseph Holt   
6      CA-2011-1510   1/2/2011  1/6/2011  Standard Class    Magdelene Morse   
7     IN-2011-79397   1/3/2011  1/3/2011        Same Day        Kean Nguyen   
8     ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
9      IZ-2011-4680   1/3/2011  1/7/2011  Standard Class   Lindsay Williams   
10    IN-2011-65159   1/3/2011  1/7/2011    Second Class       Larry Blacks   
11    IN-2011-65159   1/3/2011  1/7/2011    Second Class       Larry Blacks   
12  ES-2011-4869686   1/3/2011  1/7/2011  Standard Class  Dorothy Dickinson   
13    IN-2011-33652   1/3/2011  1/9/2011  Standard Class      Dennis Pardue   
14    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
15   MX-2011-160234   1/3/2011  1/7/2011  Standard Class   Stewart Visinsky   
16      IR-2011-770   1/3/2011  1/7/2011  Standard Class      Jas O'Carroll   
17    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
18    ID-2011-80230   1/3/2011  1/9/2011  Standard Class       Ken Lonsdale   
19    ID-2011-12596   1/3/2011  1/8/2011  Standard Class       Chris McAfee   
20    IN-2011-79397   1/3/2011  1/3/2011        Same Day        Kean Nguyen   
21     IR-2011-7690   1/3/2011  1/8/2011    Second Class         Nat Gilpin   
22      IR-2011-770   1/3/2011  1/7/2011  Standard Class      Jas O'Carroll   
23     TZ-2011-7370   1/3/2011  1/8/2011  Standard Class         Jack Garza   
24     IZ-2011-4680   1/3/2011  1/7/2011  Standard Class   Lindsay Williams   

        segment              state         country  market          region  \
0      Consumer        Constantine         Algeria  Africa          Africa   
1      Consumer    New South Wales       Australia    APAC         Oceania   
2      Consumer           Budapest         Hungary    EMEA            EMEA   
3   Home Office          Stockholm          Sweden      EU           North   
4      Consumer    New South Wales       Australia    APAC         Oceania   
5      Consumer    New South Wales       Australia    APAC         Oceania   
6      Consumer            Ontario          Canada  Canada          Canada   
7     Corporate    New South Wales       Australia    APAC         Oceania   
8      Consumer           Auckland     New Zealand    APAC         Oceania   
9     Corporate             Ninawa            Iraq    EMEA            EMEA   
10     Consumer   National Capital     Philippines    APAC  Southeast Asia   
11     Consumer   National Capital     Philippines    APAC  Southeast Asia   
12     Consumer            England  United Kingdom      EU           North   
13  Home Office            Sarawak        Malaysia    APAC  Southeast Asia   
14     Consumer           Auckland     New Zealand    APAC         Oceania   
15     Consumer          Guatemala       Guatemala   LATAM         Central   
16     Consumer               Yazd            Iran    EMEA            EMEA   
17     Consumer           Auckland     New Zealand    APAC         Oceania   
18     Consumer           Auckland     New Zealand    APAC         Oceania   
19     Consumer  Nakhon Ratchasima        Thailand    APAC  Southeast Asia   
20    Corporate    New South Wales       Australia    APAC         Oceania   
21    Corporate    Razavi Khorasan            Iran    EMEA            EMEA   
22     Consumer               Yazd            Iran    EMEA            EMEA   
23     Consumer      Dar Es Salaam        Tanzania  Africa          Africa   
24    

In [19]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... sales  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...   408   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...   120   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...    66   
3  Home Office        Stockholm     Sweden      EU    North  ...    45   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...   114   

  quantity discount   profit shipping_cost  order_priority  year  flag_profit  \
0        2      0.0  106.140         35.46          Medium  2011     positive   
1        3      0.1   36.036          9.72          Medium  2011     positive   
2        4      0.0   29.640          8.17            High  2011     positive   
3        3      0.5  -26.055          4.82            High  2011     negative   
4        5      0.1   37.770          4.70          Medium  2011     positive   

   len_cust_name flag_quantity  
0             15           low  
1             11           low  
2             13           low  
3             12           low  
4             11           low  

[5 rows x 24 columns]

In [20]:
df_sales['square_quantity'] = df_sales['quantity'].apply(lambda a : a**2)

In [21]:
df_sales.head()

order_id order_date ship_date       ship_mode    customer_name  \
0     AG-2011-2040   1/1/2011  1/6/2011  Standard Class  Toby Braunhardt   
1    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   
2     HU-2011-1220   1/1/2011  1/5/2011    Second Class    Annie Thurman   
3  IT-2011-3647632   1/1/2011  1/5/2011    Second Class     Eugene Moren   
4    IN-2011-47883   1/1/2011  1/8/2011  Standard Class      Joseph Holt   

       segment            state    country  market   region  ... quantity  \
0     Consumer      Constantine    Algeria  Africa   Africa  ...        2   
1     Consumer  New South Wales  Australia    APAC  Oceania  ...        3   
2     Consumer         Budapest    Hungary    EMEA     EMEA  ...        4   
3  Home Office        Stockholm     Sweden      EU    North  ...        3   
4     Consumer  New South Wales  Australia    APAC  Oceania  ...        5   

  discount   profit shipping_cost order_priority  year  flag_profit  \
0      0.0  106.140         35.46         Medium  2011     positive   
1      0.1   36.036          9.72         Medium  2011     positive   
2      0.0   29.640          8.17           High  2011     positive   
3      0.5  -26.055          4.82           High  2011     negative   
4      0.1   37.770          4.70         Medium  2011     positive   

   len_cust_name  flag_quantity square_quantity  
0             15            low               4  
1             11            low               9  
2             13            low              16  
3             12            low               9  
4             11            low              25  

[5 rows x 25 columns]

In [22]:
import numpy as np 

In [23]:
np.array([2,3,4,5,6])

array([2, 3, 4, 5, 6])

In [24]:
type(np.array([2,3,4,5,6]))

numpy.ndarray

In [25]:
np.array([[2,3,4] , [4,5,6]])

array([[2, 3, 4],
       [4, 5, 6]])

In [26]:
np.array([[1,2,3,4] , [ 2,3,4,5]])

array([[1, 2, 3, 4],
       [2, 3, 4, 5]])

In [27]:
l = [[1,2,3,4] , [ 2,3,4,5]]

In [28]:
l[0][0]

1

In [31]:
a = np.array([3,4,5,6] , ndmin= 4)

In [32]:
a

array([[[[3, 4, 5, 6]]]])

In [33]:
arr = np.array([[1,2,3] , [4,5,6] , [7,8,9]])

In [34]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [35]:
arr.ndim

2

In [36]:
np.random.randint(1,10,(4,4))

array([[4, 6, 6, 4],
       [7, 3, 3, 3],
       [7, 2, 5, 2],
       [2, 8, 3, 5]])

In [38]:
np.random.randint(1,9,(4,4,2))

array([[[7, 3],
        [6, 8],
        [6, 8],
        [7, 7]],

       [[2, 7],
        [8, 2],
        [1, 1],
        [1, 8]],

       [[5, 4],
        [8, 7],
        [2, 1],
        [8, 7]],

       [[5, 6],
        [8, 3],
        [8, 7],
        [1, 3]]])